from __future__ import annotations

import itertools
import re
import sqlite3
from datetime import datetime, timezone
from pathlib import Path

from .models import ProductDraft, normalize_number
from .nlp_parser import extract_attributes, remove_accents

# The numbered template shown by /taoSP: (number, ProductDraft attr, label, kind).
# giaCongTacVien is intentionally omitted — the sell web form no longer has it
# (matches ProductDraft.summary()). 14 fields, same set as the web create form.
_FIELDS: list[tuple[int, str, str, str]] = [
    (1, "ten", "Tên sản phẩm ⭐", "text"),
    (2, "maSKU", "Mã SKU ⭐", "text"),
    (3, "maVach", "Barcode", "text"),
    (4, "nhanHieu", "Nhãn hiệu", "text"),
    (5, "loaiSanPham", "Loại sản phẩm", "text"),
    (6, "viTri", "Vị trí", "text"),
    (7, "khoiLuong", "Khối lượng", "num"),
    (8, "donViTinh", "Đơn vị tính", "text"),
    (9, "giaBanLe", "Giá bán lẻ", "money"),
    (10, "giaBanBuon", "Giá bán buôn - CTV", "money"),
    (11, "giaOrder", "Giá order lẻ", "money"),
    (12, "giaOrderBuonCtv", "Giá order buôn - CTV", "money"),
    (13, "giaNhap", "Giá nhập", "money"),
    (14, "tonKhoBanDau", "Tồn kho", "int"),
]
_BY_NUM = {num: (attr, label, kind) for num, attr, label, kind in _FIELDS}

# A field marker is "<1-2 digits>:" at the start of the message or right after a
# comma / semicolon / newline. The value runs until the next marker. This lets a
# user set several fields at once ("1: giày, 9: 120000") without a value's own
# digits being mistaken for a marker (a marker MUST be followed by ':' or '=').
_MARKER_RE = re.compile(r"(?:^|[,;\n])\s*(\d{1,2})\s*[:=]\s*")
# An attribute clause ("…, màu sắc: đỏ", "…, size 21") starts a NEW segment, so
# a numbered field value must stop before it — otherwise "2: SP1, màu sắc: đỏ"
# would read the SKU as "SP1, màu sắc: đỏ". Only matches when the keyword opens
# a comma/semicolon-delimited clause, so a name like "áo màu đỏ" is left intact.
_ATTR_BOUNDARY_RE = re.compile(
    r"(?:^|[,;])\s*(?:mau\s*sac|mau|size|kich\s*thuoc|chat\s*lieu)\b"
)


def _bound_value(raw: str) -> str:
    boundary = _ATTR_BOUNDARY_RE.search(remove_accents(raw))
    if boundary:
        raw = raw[: boundary.start()]
    return raw.strip().strip(",;").strip()


# A numbered field ("…, 12: 333") that follows an attribute clause is a NEW
# field, not another attribute value — so put each such marker on its own line
# before attribute extraction, otherwise "màu sắc: 333343, 12: 333" would read
# "12: 333" as a colour value. (Mirror of _bound_value for the other direction.)
_TACH_TRUONG_SO_RE = re.compile(r"([,;])(\s*\d{1,2}\s*[:=])")


def _tach_truong_so(text: str) -> str:
    return _TACH_TRUONG_SO_RE.sub(r"\n\2", text)


def parse_numbered(text: str) -> dict[int, str]:
    result: dict[int, str] = {}
    markers = list(_MARKER_RE.finditer(text))
    for i, marker in enumerate(markers):
        num = int(marker.group(1))
        if num not in _BY_NUM:
            continue
        start = marker.end()
        end = markers[i + 1].start() if i + 1 < len(markers) else len(text)
        result[num] = _bound_value(text[start:end])
    return result


def apply_form_text(draft: ProductDraft, text: str) -> bool:
    """Apply `N: value` fields and attribute lines (màu sắc: …, size: …) to the
    draft in place. Returns True if anything recognized was applied, so the
    caller can nudge the user when a message matched nothing."""
    changed = False

    for num, raw in parse_numbered(text).items():
        attr, _, kind = _BY_NUM[num]
        if kind == "text":
            setattr(draft, attr, raw)
        elif kind in ("money", "num"):
            setattr(draft, attr, max(0.0, normalize_number(raw)))
        elif kind == "int":
            try:
                setattr(draft, attr, max(0, int(float(normalize_number(raw)))))
            except (TypeError, ValueError):
                setattr(draft, attr, 0)
        changed = True

    attributes = extract_attributes(_tach_truong_so(text))
    if attributes:
        # Merge by attribute name so attributes sent across several messages
        # ("màu sắc: …" then "size: …") accumulate instead of overwriting; a
        # repeated name updates that attribute's values. Variants are then
        # (re)generated by the sell v2 preview from thuocTinhs.
        gop: dict[str, dict] = {
            remove_accents(t.get("ten", "")).strip(): t for t in draft.thuocTinhs
        }
        for attr in attributes:
            gop[remove_accents(attr.get("ten", "")).strip()] = attr
        draft.thuocTinhs = list(gop.values())
        draft.variants = []
        changed = True

    draft.clean()
    return changed


def sinh_phien_ban(thuoc_tinhs: list[dict]) -> list[str]:
    """Cartesian product of attribute values → variant labels ("đỏ-21", …),
    matching how the sell backend expands thuocTinhs into variants. Purely for
    display in the draft so the user sees the versions before creating."""
    nhom = [t.get("giaTri", []) for t in thuoc_tinhs if t.get("giaTri")]
    if not nhom:
        return []
    return ["-".join(str(v) for v in combo) for combo in itertools.product(*nhom)]


def _hien_gia_tri(draft: ProductDraft, attr: str, kind: str) -> str:
    value = getattr(draft, attr, "")
    if kind in ("money", "num", "int"):
        return f"{float(value or 0):,.0f}" if value else "—"
    return str(value) if value else "—"


def render_form(draft: ProductDraft) -> str:
    dong = [
        "📝 Bản nháp sản phẩm — nhập theo 'số: giá trị'",
        "(vd: 1: giày admind, 9: 120000, 14: 44). ⭐ = bắt buộc.",
        "",
    ]
    for num, attr, label, kind in _FIELDS:
        dong.append(f"{num}. {label}: {_hien_gia_tri(draft, attr, kind)}")

    if draft.thuocTinhs:
        dong.append("")
        dong.append("Thuộc tính:")
        for thuoc_tinh in draft.thuocTinhs:
            dong.append(f"- {thuoc_tinh.get('ten')}: {', '.join(thuoc_tinh.get('giaTri', []))}")
        phien_ban = sinh_phien_ban(draft.thuocTinhs)
        dong.append(f"→ {len(phien_ban)} phiên bản:")
        for nhan in phien_ban[:12]:
            dong.append(f"   • {nhan}")
        if len(phien_ban) > 12:
            dong.append(f"   • … và {len(phien_ban) - 12} phiên bản nữa")

    if draft.anhChung:
        dong.append("")
        dong.append(f"Ảnh chung: {len(draft.anhChung)}")

    dong.append("")
    dong.append("Thêm phiên bản: 'màu sắc: đỏ, xanh' hoặc 'size: 21, 22'. Gõ 'hủy' để hủy.")
    return "\n".join(dong)


class FormModeStore:
    """Marks which chats are in the /taoSP guided-form mode so plain text is
    parsed as form input instead of the free-text fallback. Persisted so the
    mode survives a bot restart."""

    def __init__(self, data_dir: Path) -> None:
        self.path = data_dir / "drafts.sqlite3"
        self.path.parent.mkdir(parents=True, exist_ok=True)
        with self._connect() as db:
            db.execute(
                "CREATE TABLE IF NOT EXISTS product_form ("
                "chat_id TEXT PRIMARY KEY, updated_at TEXT NOT NULL)"
            )

    def _connect(self) -> sqlite3.Connection:
        db = sqlite3.connect(self.path, timeout=5)
        db.execute("PRAGMA busy_timeout = 5000")
        return db

    def is_on(self, chat_id: int | str) -> bool:
        with self._connect() as db:
            row = db.execute(
                "SELECT 1 FROM product_form WHERE chat_id = ?", (str(chat_id),)
            ).fetchone()
        return row is not None

    def on(self, chat_id: int | str) -> None:
        with self._connect() as db:
            db.execute(
                "INSERT INTO product_form (chat_id, updated_at) VALUES (?, ?) "
                "ON CONFLICT(chat_id) DO UPDATE SET updated_at = excluded.updated_at",
                (str(chat_id), datetime.now(timezone.utc).isoformat()),
            )

    def off(self, chat_id: int | str) -> None:
        with self._connect() as db:
            db.execute("DELETE FROM product_form WHERE chat_id = ?", (str(chat_id),))
